baseurl = "/" # domain agnostic to facilitate CNAMEs
languageCode = "en-US"
theme = "terminal"
enableEmoji = true
enableRobotsTXT = true # Suggested, enable robots.txt file
copyright = "Patrick O'Doherty :: CC-BY"

[params]
author = "patrickod" # Optional, controls author name display on posts
github = "https://github.com/patrickod"
twitter = "https://twitter.com/patrickod"
email = "hello@patrickod.com"

# terminal theme specific
themeColor = "blue"
contentTypeName = "post"
showMenuItems = 2
showLanguageSelector = false
fullWidthTheme = false
centerTheme = false


[permalinks]
post = "/:year/:month/:day/:filename"

[languages]
  [languages.en]
    languageName = "English"
    title = "slash blog"
    subTitle = "a collection of thoughts and hacks"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    
    [languages.en.params.logo]
      logoText = "slash blog"
      logoHomeLink = "/"
    
    [languages.en.menu]
      [[languages.en.menu.main]]
         identifier = "about"
         name = "About"
         url = "/about"
         
      [[languages.en.menu.main]]
         identifier = "projects"
         name = "Projects"
         url = "/projects"
