baseurl = "https://foxacid.patrickod.com/blog/"
disablePathToLower = true
languageCode = "en"
title = "slash blog"
theme = "after-dark"
copyright = "&copy; <a href=\"https://github.com/patrickod\">Patrick O'Doherty</a> 2016"
relativeURLS = true

enableRobotsTXT = true # Suggested, enable robots.txt file
googleAnalytics = "" # Optional, add tracking Id for analytics
SectionPagesMenu = "main" # Enable menu system for lazy bloggers

[permalinks]
post = "/blog/:year-:month-:day-:title/"

[params]
description = "a collection of thoughts and hacks"
author = "patrickod" # Optional, controls author name display on posts
show_menu = false # Optional, set false to disable menu entirely
powered_by = true # Optional, set false to disable theme credits

[params.seo]
google_verify = "" # Optional, Google verification code
bing_verify = "" # Optional, Bing verification code
yandex_verify = "" # Optional, Yandex verification code


[params.highlight]
style = "github"
languages = ["go", "dockerfile", "python"]

[[params.social]]
url = "https://github.com/patrickod"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/patrickod"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
