baseurl = "https://www.patrickod.com/"
disablePathToLower = true
languageCode = "en"
title = "slash blog"
subTitle = "a collection of thoughts and hacks"
theme = "ghostwriter"
copyright = "Patrick O'Doherty"
relativeURLS = false

enableRobotsTXT = true # Suggested, enable robots.txt file
googleAnalytics = "" # Optional, add tracking Id for analytics
SectionPagesMenu = "main" # Enable menu system for lazy bloggers
canonifyurls = true

[Taxonimies]
tag = "tags"

[permalinks]
post = "/:year/:month/:day/:filename"

[Author]
name = "Patrick O'Doherty"
profile = "https://twitter.com/patrickod"

[params]
intro = true
headline = "slash blog"
description = "a collection of thoughts and hacks"
author = "patrickod" # Optional, controls author name display on posts
github = "https://github.com/patrickod"
twitter = "https://twitter.com/patrickod"
email = "hello@patrickod.com"

[params.avatar]
url = "about/me.png"
height = 120
width = 120
alt = "Patrick O'Doherty"

[params.seo]
google_verify = "" # Optional, Google verification code
bing_verify = "" # Optional, Bing verification code
yandex_verify = "" # Optional, Yandex verification code

[params.highlight]
style = "github"
languages = ["go", "dockerfile", "python"]

[params.ContentLicense]
Name = "CC BY"
URL = "https://creativecommons.org/licenses/by/4.0/"

[menu]
  [[menu.main]]
    name = "About"
    weight = 1
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Projects"
    weight = 2
    identifier = "projects"
    url = "/projects/"

[Social]
twitter = "patrickod"
