baseurl = "/"
disablePathToLower = true
languageCode = "en-US"
theme = "terminal"
copyright = "Patrick O'Doherty"
relativeURLS = true

enableRobotsTXT = true # Suggested, enable robots.txt file
canonifyurls = true

[Taxonimies]
tag = "tags"

[permalinks]
post = "/:year/:month/:day/:filename"

[Author]
name = "Patrick O'Doherty"
profile = "https://twitter.com/patrickod"

[params]
author = "patrickod" # Optional, controls author name display on posts
github = "https://github.com/patrickod"
twitter = "https://twitter.com/patrickod"
email = "hello@patrickod.com"

# terminal theme specific
themeColor = "blue"
contentTypeName = "post"
showMenuItems = 2
showLanguageSelector = false
fullWidthTheme = false
centerTheme = true


[params.ContentLicense]
Name = "CC BY"
URL = "https://creativecommons.org/licenses/by/4.0/"

[languages]
  [languages.en]
    languageName = "English"
    title = "slash blog"
    subTitle = "a collection of thoughts and hacks"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    
    [languages.en.params.logo]
      logoText = "slash blog"
      logoHomeLink = "/"
    
    [languages.en.menu]
      [[languages.en.menu.main]]
         identifier = "about"
         name = "About"
         url = "/about"
         
      [[languages.en.menu.main]]
         identifier = "projects"
         name = "Projects"
         url = "/projects"
