baseurl = "https://patrickod.com"
disablePathToLower = true
languageCode = "en"
title = "slash blog | a collection of thoughts and hacks"
theme = "arabica"
copyright = "Patrick O'Doherty"
relativeURLS = false

enableRobotsTXT = true # Suggested, enable robots.txt file
googleAnalytics = "" # Optional, add tracking Id for analytics
# SectionPagesMenu = "main" # Enable menu system for lazy bloggers
section_pages_menu = "main"
canonifyurls = true

[permalinks]
post = "/blog/:year-:month-:day-:title/"

[params]
description = "a collection of thoughts and hacks"
author = "patrickod" # Optional, controls author name display on posts
show_menu = true # Optional, set false to disable menu entirely
powered_by = true # Optional, set false to disable theme credits

[params.seo]
google_verify = "" # Optional, Google verification code
bing_verify = "" # Optional, Bing verification code
yandex_verify = "" # Optional, Yandex verification code


[params.highlight]
style = "github"
languages = ["go", "dockerfile", "python"]

[menu]
  [[menu.main]]
    name = "Home"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "About"
    weight = 1
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Github"
    weight = 2
    identifier = "github"
    url = "https://github.com/patrickod"
  [[menu.main]]
    name = "Twitter"
    weight = 3
    identifier = "twitter"
    url = "https://twitter.com/patrickod"
